open_steam_bid_webdav_index:
    pattern:  /
    defaults: { _controller: OpenSteamBidWebdavBundle:Webdav:index }

open_steam_bid_webdav_folder:
    pattern:  /{path}
    defaults: { _controller: OpenSteamBidWebdavBundle:Webdav:index }
    requirements:
        path: ".+"