parameters:
#    open_steam_bid_webdav.example.class: OpenSteam\BidWebdavBundle\Example

services:
#    open_steam_bid_webdav.example:
#        class: %open_steam_bid_webdav.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    open_steam_bid_webdav.backtrace_logger_listener:
        class: OpenSteam\BidWebdavBundle\EventListener\BacktraceLoggerListener
        tags:
            - {name: "monolog.logger", channel: "backtrace"}
            - {name: "kernel.event_listener", event: "kernel.exception", method: "onKernelException"}
        arguments:
            - @logger
